package feng.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public StaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStaff_idIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaff_idIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaff_idEqualTo(Long value) {
            addCriterion("staff_id =", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotEqualTo(Long value) {
            addCriterion("staff_id <>", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idGreaterThan(Long value) {
            addCriterion("staff_id >", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idGreaterThanOrEqualTo(Long value) {
            addCriterion("staff_id >=", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idLessThan(Long value) {
            addCriterion("staff_id <", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idLessThanOrEqualTo(Long value) {
            addCriterion("staff_id <=", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idIn(List<Long> values) {
            addCriterion("staff_id in", values, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotIn(List<Long> values) {
            addCriterion("staff_id not in", values, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idBetween(Long value1, Long value2) {
            addCriterion("staff_id between", value1, value2, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotBetween(Long value1, Long value2) {
            addCriterion("staff_id not between", value1, value2, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_codeIsNull() {
            addCriterion("staff_code is null");
            return (Criteria) this;
        }

        public Criteria andStaff_codeIsNotNull() {
            addCriterion("staff_code is not null");
            return (Criteria) this;
        }

        public Criteria andStaff_codeEqualTo(String value) {
            addCriterion("staff_code =", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeNotEqualTo(String value) {
            addCriterion("staff_code <>", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeGreaterThan(String value) {
            addCriterion("staff_code >", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeGreaterThanOrEqualTo(String value) {
            addCriterion("staff_code >=", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeLessThan(String value) {
            addCriterion("staff_code <", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeLessThanOrEqualTo(String value) {
            addCriterion("staff_code <=", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeLike(String value) {
            addCriterion("staff_code like", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeNotLike(String value) {
            addCriterion("staff_code not like", value, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeIn(List<String> values) {
            addCriterion("staff_code in", values, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeNotIn(List<String> values) {
            addCriterion("staff_code not in", values, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeBetween(String value1, String value2) {
            addCriterion("staff_code between", value1, value2, "staff_code");
            return (Criteria) this;
        }

        public Criteria andStaff_codeNotBetween(String value1, String value2) {
            addCriterion("staff_code not between", value1, value2, "staff_code");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andStaff_descIsNull() {
            addCriterion("staff_desc is null");
            return (Criteria) this;
        }

        public Criteria andStaff_descIsNotNull() {
            addCriterion("staff_desc is not null");
            return (Criteria) this;
        }

        public Criteria andStaff_descEqualTo(String value) {
            addCriterion("staff_desc =", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descNotEqualTo(String value) {
            addCriterion("staff_desc <>", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descGreaterThan(String value) {
            addCriterion("staff_desc >", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descGreaterThanOrEqualTo(String value) {
            addCriterion("staff_desc >=", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descLessThan(String value) {
            addCriterion("staff_desc <", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descLessThanOrEqualTo(String value) {
            addCriterion("staff_desc <=", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descLike(String value) {
            addCriterion("staff_desc like", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descNotLike(String value) {
            addCriterion("staff_desc not like", value, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descIn(List<String> values) {
            addCriterion("staff_desc in", values, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descNotIn(List<String> values) {
            addCriterion("staff_desc not in", values, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descBetween(String value1, String value2) {
            addCriterion("staff_desc between", value1, value2, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andStaff_descNotBetween(String value1, String value2) {
            addCriterion("staff_desc not between", value1, value2, "staff_desc");
            return (Criteria) this;
        }

        public Criteria andOrg_idIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrg_idIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrg_idEqualTo(Integer value) {
            addCriterion("org_id =", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idNotEqualTo(Integer value) {
            addCriterion("org_id <>", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idGreaterThan(Integer value) {
            addCriterion("org_id >", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_id >=", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idLessThan(Integer value) {
            addCriterion("org_id <", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idLessThanOrEqualTo(Integer value) {
            addCriterion("org_id <=", value, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idIn(List<Integer> values) {
            addCriterion("org_id in", values, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idNotIn(List<Integer> values) {
            addCriterion("org_id not in", values, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idBetween(Integer value1, Integer value2) {
            addCriterion("org_id between", value1, value2, "org_id");
            return (Criteria) this;
        }

        public Criteria andOrg_idNotBetween(Integer value1, Integer value2) {
            addCriterion("org_id not between", value1, value2, "org_id");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateEqualTo(Date value) {
            addCriterion("create_date =", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThan(Date value) {
            addCriterion("create_date >", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThan(Date value) {
            addCriterion("create_date <", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIn(List<Date> values) {
            addCriterion("create_date in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNull() {
            addCriterion("state_date is null");
            return (Criteria) this;
        }

        public Criteria andState_dateIsNotNull() {
            addCriterion("state_date is not null");
            return (Criteria) this;
        }

        public Criteria andState_dateEqualTo(Date value) {
            addCriterion("state_date =", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotEqualTo(Date value) {
            addCriterion("state_date <>", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThan(Date value) {
            addCriterion("state_date >", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("state_date >=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThan(Date value) {
            addCriterion("state_date <", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateLessThanOrEqualTo(Date value) {
            addCriterion("state_date <=", value, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateIn(List<Date> values) {
            addCriterion("state_date in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotIn(List<Date> values) {
            addCriterion("state_date not in", values, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateBetween(Date value1, Date value2) {
            addCriterion("state_date between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andState_dateNotBetween(Date value1, Date value2) {
            addCriterion("state_date not between", value1, value2, "state_date");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrIsNull() {
            addCriterion("acc_nbr is null");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrIsNotNull() {
            addCriterion("acc_nbr is not null");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrEqualTo(String value) {
            addCriterion("acc_nbr =", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrNotEqualTo(String value) {
            addCriterion("acc_nbr <>", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrGreaterThan(String value) {
            addCriterion("acc_nbr >", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrGreaterThanOrEqualTo(String value) {
            addCriterion("acc_nbr >=", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrLessThan(String value) {
            addCriterion("acc_nbr <", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrLessThanOrEqualTo(String value) {
            addCriterion("acc_nbr <=", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrLike(String value) {
            addCriterion("acc_nbr like", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrNotLike(String value) {
            addCriterion("acc_nbr not like", value, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrIn(List<String> values) {
            addCriterion("acc_nbr in", values, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrNotIn(List<String> values) {
            addCriterion("acc_nbr not in", values, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrBetween(String value1, String value2) {
            addCriterion("acc_nbr between", value1, value2, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andAcc_nbrNotBetween(String value1, String value2) {
            addCriterion("acc_nbr not between", value1, value2, "acc_nbr");
            return (Criteria) this;
        }

        public Criteria andE_mailIsNull() {
            addCriterion("e_mail is null");
            return (Criteria) this;
        }

        public Criteria andE_mailIsNotNull() {
            addCriterion("e_mail is not null");
            return (Criteria) this;
        }

        public Criteria andE_mailEqualTo(String value) {
            addCriterion("e_mail =", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailNotEqualTo(String value) {
            addCriterion("e_mail <>", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailGreaterThan(String value) {
            addCriterion("e_mail >", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailGreaterThanOrEqualTo(String value) {
            addCriterion("e_mail >=", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailLessThan(String value) {
            addCriterion("e_mail <", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailLessThanOrEqualTo(String value) {
            addCriterion("e_mail <=", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailLike(String value) {
            addCriterion("e_mail like", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailNotLike(String value) {
            addCriterion("e_mail not like", value, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailIn(List<String> values) {
            addCriterion("e_mail in", values, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailNotIn(List<String> values) {
            addCriterion("e_mail not in", values, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailBetween(String value1, String value2) {
            addCriterion("e_mail between", value1, value2, "e_mail");
            return (Criteria) this;
        }

        public Criteria andE_mailNotBetween(String value1, String value2) {
            addCriterion("e_mail not between", value1, value2, "e_mail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 08 19:13:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}