package feng.model;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private Long staff_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_code
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String staff_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.passwd
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_desc
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String staff_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.org_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private Integer org_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.state
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.create_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.state_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private Date state_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.acc_nbr
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String acc_nbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.e_mail
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    private String e_mail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Long getStaff_id() {
        return staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staff_id the value for staff.staff_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setStaff_id(Long staff_id) {
        this.staff_id = staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_code
     *
     * @return the value of staff.staff_code
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getStaff_code() {
        return staff_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_code
     *
     * @param staff_code the value for staff.staff_code
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setStaff_code(String staff_code) {
        this.staff_code = staff_code == null ? null : staff_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.passwd
     *
     * @return the value of staff.passwd
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.passwd
     *
     * @param passwd the value for staff.passwd
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_desc
     *
     * @return the value of staff.staff_desc
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getStaff_desc() {
        return staff_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_desc
     *
     * @param staff_desc the value for staff.staff_desc
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setStaff_desc(String staff_desc) {
        this.staff_desc = staff_desc == null ? null : staff_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.org_id
     *
     * @return the value of staff.org_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Integer getOrg_id() {
        return org_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.org_id
     *
     * @param org_id the value for staff.org_id
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setOrg_id(Integer org_id) {
        this.org_id = org_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.state
     *
     * @return the value of staff.state
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.state
     *
     * @param state the value for staff.state
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.create_date
     *
     * @return the value of staff.create_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.create_date
     *
     * @param create_date the value for staff.create_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.state_date
     *
     * @return the value of staff.state_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public Date getState_date() {
        return state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.state_date
     *
     * @param state_date the value for staff.state_date
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setState_date(Date state_date) {
        this.state_date = state_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.acc_nbr
     *
     * @return the value of staff.acc_nbr
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getAcc_nbr() {
        return acc_nbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.acc_nbr
     *
     * @param acc_nbr the value for staff.acc_nbr
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setAcc_nbr(String acc_nbr) {
        this.acc_nbr = acc_nbr == null ? null : acc_nbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.e_mail
     *
     * @return the value of staff.e_mail
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public String getE_mail() {
        return e_mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.e_mail
     *
     * @param e_mail the value for staff.e_mail
     *
     * @mbggenerated Sat Oct 08 19:13:59 CST 2016
     */
    public void setE_mail(String e_mail) {
        this.e_mail = e_mail == null ? null : e_mail.trim();
    }
}